---
name: Manually Compile

on:
  workflow_run:
    workflows:
      - Java CI
    types:
      - completed

# Dummy
jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - run: env